### ISSUE TITLE
Leather Armor 

### ISSUE THREAD

**Issue by savesCZ** [TomasCZE7/HackerTools#2]
**Description**
If I use .setData();, armor is not colored. 

**What should happen?**
Armor should be colored because of using method setData in ItemBuilder

**For Example, How I use it:**

ItemBuilder helmet = new ItemBuilder(Material.LEATHER_HELMET).setUnbreakable(true).setData(tbPlayer.getPlayerByteData());

player.getPlayer().getInventory().setHelmet(helmet.build());

**Comment by TomasCZE7** [comment]
### Not an issue
You should use class `LeatherArmorBuilder` if you want to create colored armor. Regular ItemBuilder is working with regular ItemMeta instead of LeatherArmorMeta, so it only changes data of the item, but not color of the armor. The color of armor is changed only using LeatherArmorMeta through method `setColor(Color color);`.
